name: Crowdin Contributors

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: {}

env:
  CONTRIBUTORS_JSON_FILENAME: contributors/contributors_crowdin

jobs:
  crowdin-contributors:
    runs-on: ubuntu-latest
    if: github.repository == 'robok-inc/Robok-Engine'
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Generate Crowdin Contributors table
      id: generate_table
      uses: andrii-bodnar/action-crowdin-contributors@v2.0.0
      continue-on-error: false
      with:
        contributors_per_line: 8
        max_contributors: 32
        image_size: 64
        min_words_contributed: 100
        files: contributors/TABLE_CONTRIBUTORS_CROWDIN.md
        crowdin_project_link: "https://crowdin.com/project/robokide"
      env:
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

    - name: Write JSON report
      uses: "DamianReeves/write-file-action@master"
      with:
        path: ${{ env.CONTRIBUTORS_JSON_FILENAME }}_staging.json
        write-mode: overwrite
        contents: ${{ steps.generate_table.outputs.json_report }}

    - name: Pretty-print JSON report
      run: |
        sudo apt-get install jq
        cat ${{ env.CONTRIBUTORS_JSON_FILENAME }}_staging.json | jq '.' > ${{ env.CONTRIBUTORS_JSON_FILENAME }}.json
        rm ${{ env.CONTRIBUTORS_JSON_FILENAME }}_staging.json

    - name: Commit and Push changes
      run: |
        git config --global user.name "devsuay"
        git config --global user.email "devsuay@gmail.com"
        git add .
        git commit -m "chore: update crowdin contributors"
        git push origin main
      env:
        TOKEN: ${{ secrets.TOKEN }}
