name: GitHub Contributors

on:
  schedule:
    - cron: '0 */12 * * *'  # Executar a cada 12 horas
  workflow_dispatch: {}  # Permite a execução manual

jobs:
  github-contributors:
    runs-on: ubuntu-latest
    if: github.repository == 'gampiot-inc/Robok-IDE'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get GitHub Contributors
        id: get_contributors
        run: |
          curl -H "Authorization: token ${{ secrets.TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/contributors \
               -o contributors.json

      - name: Pretty-print JSON report
        run: |
          sudo apt-get install jq
          cat contributors.json | jq '.' > contributors_pretty.json

      - name: Upload JSON report
        uses: actions/upload-artifact@v4
        with:
          name: github-contributors-json
          path: contributors_pretty.json

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: Update GitHub Contributors report
          body: By GitHub Actions to update the list of contributors
          commit-message: "chore: update GitHub contributors report"
          committer: GitHub Actions <actions@github.com>
          branch: github-contributors/patch
