name: Notify Telegram


on:
  workflow_dispatch:
  push:
    paths:
      - .github/**
      - app/**
      - easy-ui/**
      - feature-compose/**
      - feature/**
      - gradle/**
      - images/**
      - robok/**
      - .gitignore
      - LICENSE
      - README.md
      - build.gradle.kts
      - gradle.properties
      - gradlew
      - gradlew.bat
      - renovate.json
      - settings.gradle.kts
  pull_request:
    paths:
      - .github/**
      - app/**
      - easy-ui/**
      - feature-compose/**
      - feature/**
      - gradle/**
      - images/**
      - robok/**
      - .gitignore
      - LICENSE
      - README.md
      - build.gradle.kts
      - gradle.properties
      - gradlew
      - gradlew.bat
      - renovate.json
      - settings.gradle.kts

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Notify Telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_RBKINC_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_RBKINC_CHAT_ID }}
          TELEGRAM_TOPIC_ID: 1100
        run: |
          commit_message=$(git log -1 --pretty=%B)
          commit_hash=$(git log -1 --pretty=%h)
          commit_author=$(git log -1 --pretty=%an)
          branch_name=$(git rev-parse --abbrev-ref HEAD)
          previous_commit_hash=$(git log -2 --pretty=%h | tail -n 1)
          repo_url="https://github.com/${{ github.repository }}"
          compare_url="${repo_url}/compare/${previous_commit_hash}...${commit_hash}"
          commit_url="${repo_url}/commit/${commit_hash}"
          message="🔨 [1 new commit](${compare_url}) to Robok-Engine:${branch_name}:%0A%0A[${commit_hash}](${commit_url}): ${commit_message} by ${commit_author}"
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
            -d "chat_id=${TELEGRAM_CHAT_ID}" \
            -d "parse_mode=Markdown" \
            -d "text=${message}" \
            -d "message_thread_id=${TELEGRAM_TOPIC_ID}" 