name: Notify Telegram

on:
  push:
    branches:
      - '**'
    branches-ignore:
      - 'dev/**'
  pull_request:
    branches:
      - '**'
    branches-ignore:
      - 'dev/**'
  workflow_dispatch:

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: List all files in repo
        run: ls
      
      - name: notify telegram
        uses: EverythingSuckz/github-telegram-notify@main
        continue-on-error: true
        with:
          bot_token: '${{ secrets.TELEGRAM_RBKINC_BOT_TOKEN }}'
          chat_id: '${{ secrets.TELEGRAM_RBKINC_CHAT_ID }}'
          topic_id: '${{ 1100 }}'
